---
title: A Decade of Toxic Release
authors: by Joanna Pittari and Cedar Callahan
output: github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Summary

This data comes from the Environmental Protection Agency's (EPA) Toxics Release Inventory (TRI) which is collected every year.
The EPA describes the TRI as a resource for people to learn more about chemical releases and pollution from both industrial and federal facilities.
Chemicals in the TRI are marked as potentially hazardous to human health.
The EPA states that they can cause cancer, chronic health issues, and acute health issues, as well as having significant environmental impacts.
Some of the effects on human health include neurological, developmental, reproductive, and immune issues, and environmental effects contaminate the air, water, and soil --- spreading poisonous effects to plants and wildlife.
We feel that this data is important to analyze and share because of the detrimental effects these chemicals have on people and the environment.
Additionally, we believe that the prevalence of carcinogenic chemicals, as well as PFAS (perfluoroalkyl and polyfluoroalkyl substances) and PBTs (persistent, bioaccumulative, and toxic substances) is something that everyone should have access to accurate information grounded in research and data

The TRI tracks 770 individual chemicals and 33 chemical categories and collects data each year via forms filed by facilities (facilities are required to file one form per chemical annually that they manufacture, process, or use above a certain limit).
Data collected for the TRI is annual, multimedia (tracks emissions to water, land, and air), and broad (it encompasses source reduction and pollution prevention).
The raw data from the EPA included 119 variables detailing facility information and location, toxin types, regulation and oversight, methods of disposal, and amount of toxins released (we did go through all of the variables and eliminate those we didn't feel we would use, bringing us down to 58).

Every year, new chemicals that must be reported to the EPA are added to the TRI list, which means the amount of chemical variables within this one decade of 2011-2021 goes from 513 reported chemicals to 545 reported chemicals which actually accounts for around 200 additions and many undocumented deletions of variables (not counting the 16 that were added to the dataset in 2011).
Rules on what qualifies as the threshold for reporting also change as certain chemicals fall in and out of especially-close watch.
Countrywide and statewide laws on environmental protection grant even more opportunity for data to drastically change year by year, though in technicality, the actual happenings at these facilities may not be changing much at all.

That TRI does not accurately tell us how many facilities are in the country, the extent of human health effects of chemicals, every source of pollution, nor how many chemicals a facility uses!
The TRI reporting forms must be filled out by owners and operators of facilities that meet the following three criteria, but they are not required to if they don't meet all three: - The facility falls within a TRI-covered industry sector or is federally-owned or operated; - The facility has 10 or more full-time employee equivalents; and - The facility manufactures (including import) or processes more than 25,000 pounds or otherwise uses more than 10,000 pounds of a TRI-listed chemical during a calendar year.
Note that a lower reporting threshold applies to some TRI chemicals: a threshold of 10 or 100 pounds applies to "chemicals of special concern" (e.g., persistent bioaccumulative toxic (PBT) chemicals); a threshold of 0.1 gram applies to the dioxin and dioxin-like compounds category; and a threshold of 100 pounds applies to Per- and Polyfuoroalkyl Substances (PFAS).

A few important terms for our analysis are: - Clean Air Act (a federal air pollution law from 1963 that has been consistently amended to add regulations to chemical emissions that harm human health and the environment/ozone. This does not mean that the non-act chemicals are not harmful, but that they are differently managed/regulated than the act chemicals) - PFAS (Per- and Polyfuoroalkyl Substances. According to the EPA, PFAS have been in use since the 1940s and have been shown to have a variety of adverse effects on humans and the environment. PFAS are found in drinking water, food, packaging, personal care products, and water and soil near waste sites. Some effects on humans include decreased fertility, developmental effects and delays, increased risk of certain types of cancer, and reduced immune function) - PBTs (persistantm bioaccumulative toxics) - Carcinogenic (refers to chemicals that are linked to the onset of different cancers. Only chemicals that are undoubtedly proven to have a strong link are in the YES category, so even chemicals that have a "likely-carcinogenic" status or "possibly-carcinogenic" are in the NO category, so it isn't surely accurate)

We broke our project into two broad sections: data overview and detailed analysis.
The data overview was further segmented into Location, Industry, Chemical, and Pollution analyses.
- The Location section included a map with all reported facilities, the number of facilities per state, number of facilities located on and off tribal land (and the percentage they make up), and the number of chemical reports per state.
- Our Industry analysis grouped the 30 industry sectors included in this dataset into 10 categories for easier analysis.
Then, we we looked at industry category distribution and the amount of carcinogens used in each category.
- For the Chemical analysis, we looked at the number of chemicals included in the TRI each year, the distribution of each chemical (the 5 most used chemicals are Lead (5.24%), Lead compounds (3.91%), Zinc compounds (3.79%), Nickel (3.17%), and Copper (3.08%)), and the distribution of each chemical type (Elemental Metal, Clean Air Act Chemical, Metal, Metal Category, Carcinogen, PBT, PFAS).
- Pollution analysis was the longest section in the data overview.
It includes sections with graphs of on site pollution by type and faceted by year and by general on and off site pollution and release by year.

We selected 11 chemicals for our detailed analysis (Arsenic, Styrene, Formaldehyde, Nickel, Chromium, Lead, Mercury, Ammonia, Phosphorus (yellow or white), Chloroform, and Benzo[g,h,i]perylene).
Out of these 11, 9 are Clean Air Act Chemicals, none are PFAS, 3 are PBTs, and 6 are carcinogenic.
We looked how many of these chemicals each facility in the dataset has used (only 3 have used all 11).
One important aspect of our detailed analysis was looking at chemical use on tribal lands.
We found that only one of the 11 chemicals is not used on tribal land (Phosphorus, though that is likely because there is only one facility in the entire country whose primary purpose is the production of phosphorus).
We found that Nickel, Mercury, Formaldehyde, Chromium, Chloroform, Benzo[g,h,i]perylene, and Arsenic are more prevalent on tribal land than off.
We also quickly looked at how many of these chemicals are used in each state, and found that 28 states and territories use all 11 chemicals.

We were incredibly curious about pollution trends, which proved to be much harder to visualize than we expected.
However, we did find several broad trends, which we found to be fascinating.
To visualize pollution and release, we created graphs and faceted them by chemical for each type of on site release, on site disposal, and off site disposal by type.
Finally, we looked at the chemical release by industry category per year, using the `on_site_release_total` variable as our metric and faceting by chemical.

Overall, we found that pollution and releases decreased between 2011 and 2021, 7 of the 11 chemicals we chose are used more frequently on tribal land than off, and energy recovery has increased greatly since 2011.
Broadly, we found that many types of pollution and release decreased between 2011 and 2021, however, we were not able to analyze why.
The most significant conclusion that we came to is that this is an incredibly complex issue that ideally needs multiple datasets and much longer than 5 weeks to fully analyze for any substantial conclusions.

The limitations of this dataset include: - Over 6000 of the facilities in our dataset had missing values for the parent company and standard parent company names.
- PFAS data only started being monitored in 2020 so we only have 2 years of data to account for in this decade.
It is a known subset of chemicals, but not one that contains the amount of accurate and consistent data that we would need.
- Not all industry sectors are listed in this dataset.
There are over 30, but as with every variable there are requirements and limitations for what is accepted into the data frame.
- The information on tribal land is similarly limited.
- We mentioned that the facilities are not all shown because they have to meet chemical thresholds, but some also are not shown because of the type of facility they are if private or U.S. owned but outside of North America --- the information there is very limited because it's not easily or legally federally regulated.
With more time and data, we would love to analyze the timing of regulation and chemical controls and how that impacts pollution and releases, the prevalence of chemicals used in each state, the reporting threshold, and PFAS use before 2020.
We would also have loved to go more in depth with the differences of facilities and chemical use on and off tribal land, specific health and environmental effects, and potentially analyzing all the data the TRI has collected.

## Presentation

Our presentation can be found [here](presentation/toxic_release_data_slides.pdf). However, it is a PDF file so it may not open in the source editor. 

## Data

Our data was downloaded from this [link](https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-data-files-calendar-years-1987-present).
We selected the years 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, and 2021.
We did have to manipulate the data to make it more usable, which can be found in [this](data/uncondensed_data.RMD) file.

## References

New EPA Data: Huge Amounts of PFAS Underreported and Burned.
(2021, October 21).
Www.nrdc.org.
<https://www.nrdc.org/bio/yiliqi/new-epa-data-huge-amounts-pfas-underreported-and-burned-0US> EPA.
(2013, January 31).

Toxics Release Inventory (TRI) Program \| US EPA. US EPA.
<https://www.epa.gov/toxics-release-inventory-tri-programUS> EPA.
(2021, October 14).

Our Current Understanding of the Human Health and Environmental Risks of PFAS.Www.epa.gov.
<https://www.epa.gov/pfas/our-current-understanding-human-health-and-environmental-risks-pfasUS> EPA,OEI.
(2013, March 3).

Basics of TRI Reporting \| US EPA. US EPA.
<https://www.epa.gov/toxics-release-inventory-tri-program/basics-tri-reporting>

Changes to the TRI List of Toxic Chemicals <https://www.epa.gov/system/files/documents/2023-01/TRI%20Chemical%20List%20Changes%2001%2024%202022.pdf>

Cancer Data for Chemicals Listed Under EPCRA Section 313 <https://www.epa.gov/sites/default/files/documents/hazard_cancer95.pdf>

Chronic (Non-Cancer) Toxicity Data for Chemicals Listed Under EPCRA Section 313 <https://www.epa.gov/sites/default/files/documents/hazard_chronic_non-cancer95.pdf>

Factors to Consider When Using Toxics Release Inventory Data <https://ordspub.epa.gov/ords/guideme_ext/guideme/file/ry20_advanced_concepts.pdf>
